const VOTE_DURATION = 15; //seconds
const MIN_TAG_LENGTH = 2;
const MAX_TAG_LENGTH = 32;

//common constract address keys
const KEY_ADDRESS_TAGS = "KEY_ADDRESS_TAGS";
const KEY_ADDRESS_VOTING_OPINIONS = "KEY_ADDRESS_VOTING_OPINIONS";
const KEY_ADDRESS_VOTING_DEBATES = "KEY_ADDRESS_VOTING_DEBATES";
const KEY_ADDRESS_DEBATES = "KEY_ADDRESS_DEBATES";
const KEY_ADDRESS_OPINIONS = "KEY_ADDRESS_OPINIONS";
const KEY_ADDRESS_TOKEN = "KEY_ADDRESS_TOKEN";

//initial reward/punishment fractions

const CONTRACT_FRACTIONS = {
    DEBATE_CREATOR_PUNISHMENT_NUMERATOR: 500,
    DEBATE_CREATOR_PUNISHMENT_DENOMINATOR: 1000,
    DEBATE_MAJORITY_VOTER_REWARD_NUMERATOR: 500,
    DEBATE_MAJORITY_VOTER_REWARD_DENOMINATOR: 1000,
    DEBATE_CREATOR_REWARD_NUMERATOR: 25,
    DEBATE_CREATOR_REWARD_DENOMINATOR: 1000,
    OPINION_CREATOR_REWARD_NUMERATOR: 500,
    OPINION_CREATOR_REWARD_DENOMINATOR: 1000,
    OPINION_MAJORITY_VOTER_REWARD_NUMERATOR: 450,
    OPINION_MAJORITY_VOTER_REWARD_DENOMINATOR: 1000,
    OPINION_DEV_REWARD_NUMERATOR: 25,
    OPINION_DEV_REWARD_DENOMINATOR: 1000
}

//FYI token constants
const TOKEN_SYMBOL = "FYI";
const TOKEN_NAME = "FYI"
const TOKEN_RESERVE_RATIO = 500000;// Out of 1 million

module.exports = {
    TOKEN_SYMBOL,
    TOKEN_NAME,
    TOKEN_RESERVE_RATIO,
    VOTE_DURATION,
    MIN_TAG_LENGTH,
    MAX_TAG_LENGTH,
    KEY_ADDRESS_TAGS,
    KEY_ADDRESS_VOTING_OPINIONS,
    KEY_ADDRESS_VOTING_DEBATES,
    KEY_ADDRESS_DEBATES,
    KEY_ADDRESS_OPINIONS,
    KEY_ADDRESS_TOKEN,
    CONTRACT_FRACTIONS
};